### ISSUE TITLE
reading zmatrix issue

### ISSUE THREAD

**Issue by Balasubra** [mcocdawc/chemcoord#58] opened 2019-08-13 15:39 UTC
I wrote a zmatrix of water dimer taking water.xyz provided in the chemcoord tests/structures folder as follows,
```python
fin = cc.Cartesian.read_xyz('water.xyz',start_index=1)
zfin = fin.get_zmat().to_zmat(upper_triangle=False)
fout = open('water.zmat','w')
fout.write(zfin)
fout.close()
```
The resulting zmatrix file when read with chemcoord as: `cc.Zmat.read_zmat('water.zmat')` throws me the following error. Could this be related to the pandas verion (0.23.4) i am using ?
```
~/MINICONDA3/lib/python3.6/site-packages/pandas/core/internals.py in _maybe_compare(a, b, op)
   5163         raise TypeError(
   5164             "Cannot compare types {a!r} and {b!r}".format(a=type_names[0],
-> 5165                                                           b=type_names[1]))
   5166     return result
   5167 

TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'
```

**Comment by mcocdawc** [comment] 2019-08-17 14:06
Thank you very much for the report. 
It is solved in the master branch now.

**Comment by mcocdawc** [comment] 2019-08-17 14:10
Note, that you can directly support a buffer/filepath instead of manually opening and closing a file:
```
fin.get_zmat().to_zmat('water.zmat', upper_triangle=True)
```

**Comment by Balasubra** [comment] 2019-08-18 12:33
Thanks. I will try in the new version.

**Comment by Balasubra** [comment] 2019-08-18 13:05
The error seems to exist, i already updated chemcoord to latest master version,
fin = cc.Cartesian.read_xyz('water.xyz',start_index=1)
fin.get_zmat().to_zmat('water.zmat', upper_triangle=True)
fin = cc.Zmat.read_zmat('water.zmat').

I am copying the complete error profile.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-b598eeac7aae> in <module>
----> 1 fin = cc.Zmat.read_zmat('water.zmat')

~/MINICONDA3/lib/python3.6/site-packages/chemcoord/internal_coordinates/_zmat_class_io.py in read_zmat(cls, inputfile, implicit_index)
    133         zmat_frame = cls._cast_correct_types(zmat_frame)
    134         try:
--> 135             Zmat = cls(zmat_frame)
    136         except InvalidReference:
    137             raise UndefinedCoordinateSystem(

~/MINICONDA3/lib/python3.6/site-packages/chemcoord/internal_coordinates/_zmat_class_core.py in __init__(self, frame, metadata, _metadata)
     73                 _metadata['has_dummies'] = {}
     74 
---> 75         fill_missing_keys_with_defaults(self._metadata)
     76 
     77     def copy(self):

~/MINICONDA3/lib/python3.6/site-packages/chemcoord/internal_coordinates/_zmat_class_core.py in fill_missing_keys_with_defaults(_metadata)
     69         def fill_missing_keys_with_defaults(_metadata):
     70             if 'last_valid_cartesian' not in _metadata:
---> 71                 _metadata['last_valid_cartesian'] = self.get_cartesian()
     72             if 'has_dummies' not in _metadata:
     73                 _metadata['has_dummies'] = {}

~/MINICONDA3/lib/python3.6/site-packages/chemcoord/internal_coordinates/_zmat_class_core.py in get_cartesian(self)
    641 
    642         c_table = self.loc[:, ['b', 'a', 'd']]
--> 643         c_table = c_table.replace(constants.int_label)
    644         c_table = c_table.replace({k: v for v, k in enumerate(c_table.index)})
    645         c_table = c_table.values.astype('i8').T

~/MINICONDA3/lib/python3.6/site-packages/pandas/core/frame.py in replace(self, to_replace, value, inplace, limit, regex, method)
   3796                                               value=value, inplace=inplace,
   3797                                               limit=limit, regex=regex,
-> 3798                                               method=method)
   3799 
   3800     @Appender(_shared_docs['shift'] % _shared_doc_kwargs)

~/MINICONDA3/lib/python3.6/site-packages/pandas/core/generic.py in replace(self, to_replace, value, inplace, limit, regex, method)
   5800 
   5801             return self.replace(to_replace, value, inplace=inplace,
-> 5802                                 limit=limit, regex=regex)
   5803         else:
   5804 

~/MINICONDA3/lib/python3.6/site-packages/pandas/core/frame.py in replace(self, to_replace, value, inplace, limit, regex, method)
   3796                                               value=value, inplace=inplace,
   3797                                               limit=limit, regex=regex,
-> 3798                                               method=method)
   3799 
   3800     @Appender(_shared_docs['shift'] % _shared_doc_kwargs)

~/MINICONDA3/lib/python3.6/site-packages/pandas/core/generic.py in replace(self, to_replace, value, inplace, limit, regex, method)
   5849                                                        dest_list=value,
   5850                                                        inplace=inplace,
-> 5851                                                        regex=regex)
   5852 
   5853                 else:  # [NA, ''] -> 0

~/MINICONDA3/lib/python3.6/site-packages/pandas/core/internals.py in replace_list(self, src_list, dest_list, inplace, regex, mgr)
   3737             return _maybe_compare(values, getattr(s, 'asm8', s), operator.eq)
   3738 
-> 3739         masks = [comp(s) for i, s in enumerate(src_list)]
   3740 
   3741         result_blocks = []

~/MINICONDA3/lib/python3.6/site-packages/pandas/core/internals.py in <listcomp>(.0)
   3737             return _maybe_compare(values, getattr(s, 'asm8', s), operator.eq)
   3738 
-> 3739         masks = [comp(s) for i, s in enumerate(src_list)]
   3740 
   3741         result_blocks = []

~/MINICONDA3/lib/python3.6/site-packages/pandas/core/internals.py in comp(s)
   3735             if isna(s):
   3736                 return isna(values)
-> 3737             return _maybe_compare(values, getattr(s, 'asm8', s), operator.eq)
   3738 
   3739         masks = [comp(s) for i, s in enumerate(src_list)]

~/MINICONDA3/lib/python3.6/site-packages/pandas/core/internals.py in _maybe_compare(a, b, op)
   5163         raise TypeError(
   5164             "Cannot compare types {a!r} and {b!r}".format(a=type_names[0],
-> 5165                                                           b=type_names[1]))
   5166     return result
   5167 

TypeError: Cannot compare types 'ndarray(dtype=int64)' and 'str'

**Comment by mcocdawc** [comment] 2019-08-18 15:51
I cannot reproduce your error.
Are you sure, that you

1. Pulled the new code **and**
2. Installed the new version?

What does `cc.__version__` give you?
It should be `'2.0.4.post4'`.

PS: For such cases it might be handy, to install via `pip install -ve .` 
The `-e` option creates only symlinks to your code repository. Your installation becomes then automatically updated if files are changed.

PPS: If you use  three backticks ` ``` ` you get multiline formatted code in GitHub issues.

**Comment by Balasubra** [comment] 2019-08-18 16:21
Thank you, yes it was just an update problem. Initially i used conda to update, later cloned via git and installed with pip, now it is up-to-date and the issue is solved.

**Comment by mcocdawc** [comment] 2019-08-18 16:37
Perfect.

**Closed by mcocdawc** 2019-08-18 16:37 UTC
Labels: bug
